### ISSUE TITLE
校友强啊

### ISSUE THREAD

**Issue by newcovid** [skyilz/HAUT_englishclock_check#1]
今天又打卡想着上来逛逛有没有，没想到还真有，那我只好给你star了

**Comment by iskyil** [comment]
xD

谁让补卡次数只有三次呢(

**Comment by newcovid** [comment]
但是好像有点BUG
 pic = data['data']['submit_list'][rand]['picture_list'][0]
IndexError: list index out of range
我把rand范围调成0，45了
最后requests返回了{'err_code': 100, 'err_msg': 'ERR_INVALID_REQ'}
希望能解决

**Comment by iskyil** [comment]
> 但是好像有点BUG pic = data['data']['submit_list'][rand]['picture_list'][0] IndexError: list index out of range 我把rand范围调成0，45了 最后requests返回了{'err_code': 100, 'err_msg': 'ERR_INVALID_REQ'} 希望能解决

ERR_INVALID_REQ这个bug，今天中午已经修复了。
还有你提的数组超限问题，我中午也发现了，不过因为下午全是课，要等晚上才能修复了。

**Comment by iskyil** [comment]
> 但是好像有点BUG pic = data['data']['submit_list'][rand]['picture_list'][0] IndexError: list index out of range 我把rand范围调成0，45了 最后requests返回了{'err_code': 100, 'err_msg': 'ERR_INVALID_REQ'} 希望能解决

尝试修复了数组超限的bug,你可以试一下
